import "./globals.css";
import { CVContextProvider, useCVContext } from "../context/cv-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CVContextProvider>{children}</CVContextProvider>
      </body>
    </html>
  );
}
